mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


# 指定全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml

#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql